[build]
  command = "npm run build"
[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"